### ISSUE TITLE
Clarification about the experiment setting in the paper

### ISSUE THREAD

**Issue by kerkathy** [parthsarthi03/raptor#13]
Hi, thanks for the work and I found the idea really interesting!

Since I wanted to make a reproduction of the experiments, I have a small question. To my knowledge, your method is to build the tree first and query the tree later. However, in the QuALITY dataset, there is one passage of around 5000 tokens for each question. In this case, do you build one tree for each question using the passage corresponding to that specific question? 
Also, for the other datasets (NarrativeQA and QASPER), do you build a shared tree for all questions?

thanks again for your kind sharing!

**Comment by parthsarthi03** [comment]
Hi! Thanks for your interest in the work! To clarify, the tree-building process is passage-specific but question-independent. For each dataset, we build one tree per passage. Since each passage has multiple associated questions, the same tree is used to answer all questions for that passage.

**Comment by kerkathy** [comment]
Thanks for your prompt and clear explanation 😄

**Comment by Ningyu-y** [comment]
Hello, can you share the experimental code, thank you very much
