### ISSUE TITLE
Question about experiment

### ISSUE THREAD

**Issue by liuxinbin12138** [parthsarthi03/raptor#18]
In the paper's experimental section, is the tree constructed using multiple documents or just a single document? Based on the code, it appears that a tree can only be constructed using one document. I look forward to your response!

**Comment by parthsarthi03** [comment]
Hey! We build one tree per document.

**Comment by hippoley** [comment]
It's more like a Directed Acyclic Graph (DAG) when compared to a tree.

**Comment by liuxinbin12138** [comment]
> Hey! We build one tree per document.

thx a lot
