### ISSUE TITLE
Support for Azure OpenAi

### ISSUE THREAD

**Issue by ferrygun** [parthsarthi03/raptor#21]
Hi, do you have a plan to support Azure OpenAI in the near future?

**Comment by parthsarthi03** [comment]
Hi! RAPTOR can be currently used with any inference setup. You can define your own inference code to use Azure OpenAI by defining your custom SummarizationModel, QAModel, and Embedding model. We have a tutorial for this available [here](https://github.com/parthsarthi03/raptor/blob/master/demo.ipynb).

**Comment by ferrygun** [comment]
Got it. Thank you!

**Comment by ferrygun** [comment]
Got it. Thank you!
