### ISSUE TITLE
Constructing Layer Issue

### ISSUE THREAD

**Issue by medxiaorudan** [parthsarthi03/raptor#23]
Hello, I have different length of samples, the num_layers range from 17 to 51, but all of them "Stopping Layer construction: Cannot Create More Layers. Total Layers in tree: 2", it seems I can't build a tree more than 2 layers.

**Comment by parthsarthi03** [comment]
Hey! How long are your texts? The algorithm stops the layer construction if it cannot cluster anymore.

**Comment by medxiaorudan** [comment]
> Hey! How long are your texts? The algorithm stops the layer construction if it cannot cluster anymore.

Thanks for your reply, my texts were retrieved from Pinecone vector database and they are of different lengths ranging from 766 to 6047 tokens. All of them stop the layer construction at layer 2.

**Comment by parthsarthi03** [comment]
At that length, two layers would be standard. We're coming out with new clustering methods soon that will allow you to have more explicit control over the number of layers. Meanwhile, if you want more layers, you could decrease your chunk token length. You can do that by 

```python
RAC = RetrievalAugmentationConfig(tb_max_tokens=50) 
RA = RetrievalAugmentation(config=RAC)
RA.add_documents(text)
```
here the chunk size is a maximum of 50 tokens (by default it is 100).
