### ISSUE TITLE
How put my own inference logic

### ISSUE THREAD

**Issue by johngonzalez** [parthsarthi03/raptor#4]
Thanks for your work. I have chat logic with my own code. For example I must use Azure Open AI. How I could incluye My own inference logic in some class using the raptor methodogy?

**Comment by parthsarthi03** [comment]
Hey! You can define your own inference code by defining your custom SummarizationModel, QAModel, and Embedding model. We have a tutorial for this available [here](https://github.com/parthsarthi03/raptor/blob/master/demo.ipynb).

**Comment by johngonzalez** [comment]
Thanks, that is true. The library is very flexible. Maybe should be good idea make simple examples of this.
